### ISSUE TITLE
作品问题

### ISSUE THREAD

**Issue by Kiwamm** [QIN2DIM/CNJSJ_DataMining#1]
你好，可以问下你是拿这个项目拿了国二吗

**Comment by Kiwamm** [comment]
你是怎么看到那个红楼梦的演示图的呀，我去官网找的时候只能看到获奖人名字和项目名字

**Comment by QIN2DIM** [comment]
这是作者提交的材料。如有冒犯我会更换插图…

**Comment by QIN2DIM** [comment]
> 你好，可以问下你是拿这个项目拿了国二吗

没理解您的问题，可以重述一下吗

**Comment by Kiwamm** [comment]
> 这是作者提交的材料。如有冒犯我会更换插图…
没有没有，我是想问下作者提交的材料可以在哪看啊，我只能看到获奖人名单那个pdf

**Comment by Kiwamm** [comment]
> > 你好，可以问下你是拿这个项目拿了国二吗
> 
> 没理解您的问题，可以重述一下吗

我看你前面说你参加了一次，获得了大数据赛道国二，想知道你是用这个项目获得的国二吗。。我想看下这个比赛大概的水平是咋样的

**Comment by Kiwamm** [comment]
> > > 你好，可以问下你是拿这个项目拿了国二吗
> > 
> > 
> > 没理解您的问题，可以重述一下吗
> 
> 我看你前面说你参加了一次，获得了大数据赛道国二，想知道你是用这个项目获得的国二吗。。我想看下这个比赛大概的

> > > 你好，可以问下你是拿这个项目拿了国二吗
> > 
> > 
> > 没理解您的问题，可以重述一下吗
> 
> 我看你前面说你参加了一次，获得了大数据赛道国二，想知道你是用这个项目获得的国二吗。。我想看下这个比赛大概的水平是咋样的

因为我来年想参加的试试，所以想看下这个比赛大概什么水平可以获奖，，，没有别的意思

**Comment by QIN2DIM** [comment]
> > > > 你好，可以问下你是拿这个项目拿了国二吗
> > > 
> > > 
> > > 没理解您的问题，可以重述一下吗
> > 
> > 
> > 我看你前面说你参加了一次，获得了大数据赛道国二，想知道你是用这个项目获得的国二吗。。我想看下这个比赛大概的
> 
> > > > 你好，可以问下你是拿这个项目拿了国二吗
> > > 
> > > 
> > > 没理解您的问题，可以重述一下吗
> > 
> > 
> > 我看你前面说你参加了一次，获得了大数据赛道国二，想知道你是用这个项目获得的国二吗。。我想看下这个比赛大概的水平是咋样的
> 
> 因为我来年想参加的试试，所以想看下这个比赛大概什么水平可以获奖，，，没有别的意思

这个比赛还挺有趣的，有很多方向的赛道，不同赛道的主题、评审、“卷度”差距蛮大的，“艺术类”方向里有很多让我非常惊艳的学生作品，“编程类”则梯度差距明显，有很多比较简单的代码实现，也有凤毛麟角的成熟的思路新颖的计算机作品。

我们团队拿了大数据实践赛的国一，设计的系统有一篇1区的SCI论文作理论支持，有落地的后端系统和大屏可视化前端。

这个git项目是一个非常简单的爬虫脚本，我大概一个小时就写完了…我甚至没有点开流程设计的软件…上述系统从调研到落地花了好几个月来着（记不太清）。

**Comment by QIN2DIM** [comment]
> 因为我来年想参加的试试，所以想看下这个比赛大概什么水平可以获奖

“编程类”有很多赛道，小伙伴可以在赛务手册里研究一下不同赛道的主题和评审标准。我个人感觉，这是一个本硕群体开展的比赛，除了极个别的参赛者，设计思维差距不大，有过大型项目开发经验的更是凤毛麟角，大多数人起点都一样。

个人认为获奖的关键是“成熟”和“创新”，充分的需求分析+稳定上线的系统+合理新颖的应用场景->解决痛点。我大概看了一下，有很多“小程序”和“WEB开发”的项目都“撞车”了，面向的都是已饱和的传统的需求，而且作品可靠程度不高，大多是能一下午就能撸出来的作品或者是git上已有的成熟项目的修改包装。“AI”“大数据”之类的门槛较高，参赛作品相对较少。

我大概看了一下国赛获奖名单，名校大佬不是很多。大多是本科双非的学生参加，分本科赛道和专科赛道。

**Comment by Kiwamm** [comment]
> 下国赛获奖名单，名校大佬不是很多。大多是本科双非的学生参加，分本科赛道和专科赛道。

哦哦，谢谢了！

**Comment by Kiwamm** [comment]
> > 因为我来年想参加的试试，所以想看下这个比赛大概什么水平可以获奖
> 
> “编程类”有很多赛道，小伙伴可以在赛务手册里研究一下不同赛道的主题和评审标准。我个人感觉，这是一个本硕群体开展的比赛，除了极个别的参赛者，设计思维差距不大，有过大型项目开发经验的更是凤毛麟角，大多数人起点都一样。
> 
> 个人认为获奖的关键是“成熟”和“创新”，充分的需求分析+稳定上线的系统+合理新颖的应用场景->解决痛点。我大概看了一下，有很多“小程序”和“WEB开发”的项目都“撞车”了，面向的都是已饱和的传统的需求，而且作品可靠程度不高，大多是能一下午就能撸出来的作品或者是git上已有的成熟项目的修改包装。“AI”“大数据”之类的门槛较高，参赛作品相对较少。
> 
> 我大概看了一下国赛获奖名单，名校大佬不是很多。大多是本科双非的学生参加，分本科赛道和专科赛道。

原来是大佬，失敬失敬
