### ISSUE TITLE
m1 python3.9解码错误

### ISSUE THREAD

**Issue by lisicn** [QIN2DIM/CNJSJ_DataMining#2]
M1 芯片下，python3.9，
解决由于服务端response的文件编码问题导致的解码失败。
【add】cnjsj.py   +121 :
        res.encoding = "utf-8"

另外：
你的思路很清晰，当我看了你的\n
代码时，没多久就明白了，\n
有点不爽的就是\n
拉代码的时候网络卡顿了一下，\n
及时设置代理就好了:)

**Comment by QIN2DIM** [comment]
maybe...暂时无法搭建错误环境，我在win上跑是正常的
