### ISSUE TITLE
4C-2020 MHTML 作品镜像备份

### ISSUE THREAD

**Issue by Nevermindss** [QIN2DIM/CNJSJ_DataMining#4]

**Comment by QIN2DIM** [comment]
## MHTML 作品镜像备份
链接：https://pan.baidu.com/s/1ylVJEfCgDNBuPdva9ls7CQ?pwd=j494 
提取码：j494
备注：可以用浏览器打开 MHTML 格式文件（如 Chrome/Edge/Firefox）
## 作品索引查询 ID/作品名/名词/院校/成员

https://github.com/QIN2DIM/4C-ExcellentProject/blob/master/database/id_set_01.csv

**Comment by Nevermindss** [comment]
非常感谢您！祝您学业顺利，工作顺利
________________________________
发件人: QIN2DIM ***@***.***>
发送时间: 2023年3月2日 8:01
收件人: QIN2DIM/4C-ExcellentProject ***@***.***>
抄送: Nevermindss ***@***.***>; Author ***@***.***>
主题: Re: [QIN2DIM/4C-ExcellentProject] 你好，目前20年的作品展示网站已经进不去了，请问您那里还有留存的离线作品展示吗 (Issue #4)


MHTML 作品镜像备份

链接：https://pan.baidu.com/s/1ylVJEfCgDNBuPdva9ls7CQ?pwd=j494
提取码：j494

―
